<a href="https://colab.research.google.com/github/Shiva-panda/python/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [33]:
#numpy >> numerical python
#2005 by Travis Oliphant

In [34]:
import numpy as np

In [35]:
np.__version__

'2.0.2'

In [36]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [37]:
lis = [1, 2, 3, "pwskills", 3+5j, True, 1.2]
type(lis)


In [39]:
lis

[1, 2, 3, 'pwskills', (3+5j), True, 1.2]

In [40]:
#Numpy stores the data in an array
#An array is a container used to store the data of same data type


In [41]:
#why numpy
#Computation is fast>> due to array>>>continous memory location
#mathematical computation

In [42]:
l = [1, 2, 3, 4, 5]
arr = np.array(l)

In [44]:
arr

array([1, 2, 3, 4, 5])

In [45]:
l = [1, 2, 3, 4, 5.1]
arr = np.array(l)

In [46]:
arr

array([1. , 2. , 3. , 4. , 5.1])

In [47]:
l = [1, 2, 3, 4, 5.1, "Ajay"]
arr = np.array(l)

In [48]:
arr

array(['1', '2', '3', '4', '5.1', 'Ajay'], dtype='<U32')

In [49]:
#arr stores homogenous data

In [50]:
type(arr)
arr.ndim

numpy.ndarray

In [52]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])

In [112]:
print(arr1)
print("the dimrension of the matrix is",arr1.ndim)

[[ True False False]
 [False  True False]
 [False False  True]]
the dimrension of the matrix is 2


In [55]:
mat = np.matrix([1, 2, 3, 4]) #matrix is a specialised array, 2 dimensional

In [56]:
type(mat)

numpy.matrix

In [57]:
#more way to convert array
l = [1, 2, 3]
np.asarray(l)

array([1, 2, 3])

In [58]:
mat

matrix([[1, 2, 3, 4]])

In [59]:
np.asarray(mat)

array([[1, 2, 3, 4]])

In [60]:
np.asanyarray([1, 2, 3])

array([1, 2, 3])

In [61]:
mat

matrix([[1, 2, 3, 4]])

In [62]:
np.asanyarray(mat) #Convert the input to an ndarray, but pass ndarray subclasses through.

matrix([[1, 2, 3, 4]])

In [63]:
t = ([1, 2, 3], [4, 5, 6]) #tuple to array

In [64]:
type(t)

tuple

In [65]:
np.array(t)

array([[1, 2, 3],
       [4, 5, 6]])

In [66]:
l = [1, 2, 3, 4, 5]
arr = np.array(l)

In [67]:
arr

array([1, 2, 3, 4, 5])

In [68]:
arr[0] = 500

In [69]:
arr

array([500,   2,   3,   4,   5])

In [70]:
arr

array([500,   2,   3,   4,   5])

In [71]:
a = arr

In [72]:
a

array([500,   2,   3,   4,   5])

In [73]:
arr[0] = 1000

In [74]:
a #change in array also lead to change in a >> shallow copy

array([1000,    2,    3,    4,    5])

In [75]:
a = arr.copy()

In [76]:
a

array([1000,    2,    3,    4,    5])

In [77]:
arr

array([1000,    2,    3,    4,    5])

In [78]:
arr[0] = 2000

In [79]:
arr

array([2000,    2,    3,    4,    5])

In [80]:
a

array([1000,    2,    3,    4,    5])

In [81]:
#To create an array >> np.array, np.asarray, np.asanyarray, deep copy and shallow copy

In [82]:
#multiple ways to generate array

In [83]:
arr1 = np.fromfunction(lambda i, j : i==j, (3,3)) #Construct an array by executing a function over each coordinate.

In [84]:
arr1

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [85]:
arr1.ndim

2

In [86]:
arr1.shape #shape of array

(3, 3)

In [87]:
arr1.size #no of elements in array

9

In [88]:
arr2 = np.fromfunction(lambda i, j : i*j, (3,3))

In [89]:
arr2

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [90]:
for i in range(5):
    print(i)

0
1
2
3
4


In [91]:
[i for i in range(5)]

[0, 1, 2, 3, 4]

In [92]:
list((i for i in range(5)))

[0, 1, 2, 3, 4]

In [93]:
iterable = (i for i in range(5))

In [94]:
np.fromiter(iterable, int) #Create a new 1-dimensional array from an iterable object.

array([0, 1, 2, 3, 4])

In [95]:
np.fromstring('22 23 24', sep = " ") #values should be numerical

array([22., 23., 24.])

In [96]:
np.fromstring('22,23,24', sep = ",")

array([22., 23., 24.])

In [97]:
#for string character you have  to use split
string = 'Ajay,Bijay,Sanjay'
string1 = string.split(',')
np.array(string1)

array(['Ajay', 'Bijay', 'Sanjay'], dtype='<U6')

In [98]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [99]:
range(10)

range(0, 10)

In [100]:
#other methods of numpy>> to generate sequnce of nos
np.arange(1, 10, 0.1) #Return evenly spaced values within a given interval.

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1,
       6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4,
       7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7,
       8.8, 8.9, 9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [113]:
np.linspace(1, 5, 10)#Return evenly spaced numbers over a specified interval.
#give me 10 numbers between 1 and 5 evenly spaced

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [114]:
v=np.array([[1,2,32],[4,5,6],[7,8,9]])

In [105]:
v

array([[[1, 2, 3],
        [4, 5, 6]]])

In [106]:
v.ndim

3